blog/urls.py
from django.conf.urls import url
from .views import ArticleListView, ArticleDetailView, ArticleLike, ArticleComment


urlpatterns = [
    url(r'^$', ArticleListView.as_view(), name='article_list'),
    url(r'^(?P<category_slug>[\w-]+)/$', ArticleListView.as_view(), name='article_list'),
    url(r'^article/(?P<slug>[-\w]+)/$', ArticleDetailView.as_view(), name='article_detail'),
    url(r'^article/(?P<slug>[-\w]+)/like/$', ArticleLike, name='article_like'),
    url(r'^article/(?P<slug>[-\w]+)/comment/$', ArticleComment.as_view(), name='article_comment'),
]

test_the_invaders/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^ext/', include('city.urls', namespace='city')),
    url(r'^', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from ckeditor.fields import RichTextField
from city.models import City, ExtUser
import PIL
from django.core.urlresolvers import reverse_lazy


class ArticleCategory(models.Model):
    title = models.CharField('Название', max_length=150)
    text = RichTextUploadingField(config_name='full')
    slug = models.SlugField('Slug', unique=True, blank=True)

    def get_absolute_url(self):
        return reverse_lazy('article_category', args=[str(self.slug)])

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Категория статей'
        verbose_name_plural = 'Категории статей'


class Comment(models.Model):
    extuser = models.ForeignKey(ExtUser)
    body = RichTextField(config_name='text')

    def __str__(self):
        return self.extuser.user.username

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


class Article(models.Model):
    title = models.CharField('Название', max_length=150)
    text = RichTextUploadingField(config_name='full')
    slug = models.SlugField('Slug', unique=True, blank=True)
    city = models.ForeignKey(City, verbose_name='Город')
    date = models.DateTimeField('Время и дата публикации')
    image = models.ImageField('Главное изображение', upload_to='articles/')

    categorys = models.ManyToManyField(ArticleCategory, verbose_name='Категории')

    comments = models.ManyToManyField(Comment, verbose_name='Комментарии', blank=True)
    likes = models.ManyToManyField(ExtUser, related_name='likes', blank=True)
    dislikes = models.ManyToManyField(ExtUser, related_name='dislikes', blank=True)

    def get_likes_count(self):
        return self.likes.count()

    def get_dislikes_count(self):
        return self.dislikes.count()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

blog/forms.py
from django.forms import ModelForm
from .models import Comment


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['body']

blog/views.py
from django.views.generic import ListView, DetailView, FormView
from .models import Article, ArticleCategory, Comment
from .forms import CommentForm
from city.models import ExtUser
from django.shortcuts import redirect
from django.core.urlresolvers import reverse_lazy
from django.http import JsonResponse
from django.http.response import HttpResponse


class ArticleListView(ListView):
    model = Article
    paginate_by = 3

    # def get(self, request, *args, **kwargs):
    #     if request.user.is_authenticated:
    #         if request.user.extuser:
    #             return super(ArticleListView, self).get(request, *args, **kwargs)
    #         else:
    #             return redirect(reverse_lazy('city:choose_city'))
    #     else:
    #         return redirect(reverse_lazy('city:create_extuser'))

    def get_queryset(self):
        category_slug = self.kwargs.get('category_slug', None)
        if category_slug:
            if hasattr(self.request.user, 'extuser'):
                return Article.objects.filter(city=self.request.user.extuser.city, categorys__slug=category_slug).order_by('date')
            else:
                return Article.objects.filter(categorys__slug=category_slug).order_by('date')
        else:
            if hasattr(self.request.user, 'extuser'):
                return Article.objects.filter(city=self.request.user.extuser.city).order_by('date')
            else:
                return Article.objects.all().order_by('date')

    def get_context_data(self, **kwargs):
        context = super(ArticleListView, self).get_context_data(**kwargs)
        if hasattr(self.request.user, 'extuser'):
            context['categories_list'] = ArticleCategory.objects.filter(article__city=self.request.user.extuser.city).distinct()
        else:
            context['categories_list'] = ArticleCategory.objects.all().distinct()
        context['category_slug'] = self.kwargs.get('category_slug', None)
        return context


class ArticleDetailView(DetailView):
    model = Article
    template_name = 'blog/article_detail.html'
    comment_form = CommentForm

    def get_context_data(self, **kwargs):
        context = super(ArticleDetailView, self).get_context_data(**kwargs)
        if hasattr(self.request.user, 'extuser'):
            context['categories_list'] = ArticleCategory.objects.filter(article__city=self.request.user.extuser.city).distinct()
        else:
            context['categories_list'] = ArticleCategory.objects.all().distinct()
        article = Article.objects.get(slug=self.kwargs.get('slug', None))
        if hasattr(self.request.user, 'extuser'):
            if not article.comments.filter(article__comments__extuser=ExtUser.objects.get(user=self.request.user)):
                context['comment_form'] = self.comment_form
        return context


def ArticleLike(request, slug):
    if request.is_ajax():
        extUser = request.user.extuser
        article = Article.objects.get(slug=slug)
        likes = article.likes.all()
        likes_count = len(likes)
        dislikes = article.dislikes.all()
        dislikes_count = len(dislikes)
        answer = {'likes_count': likes_count, 'dislikes_count': dislikes_count}
        if extUser in likes or extUser in dislikes:
            answer.update({'result': False})
            return JsonResponse(answer)
        else:
            action = request.GET.get('action', 'like')
            if action == 'like':
                article.likes.add(extUser)
                likes_count += 1
            else:
                article.dislikes.add(extUser)
                dislikes_count += 1
            answer.update({'result': True, 'action': action, 'likes_count': likes_count, 'dislikes_count': dislikes_count})
            return JsonResponse(answer)
    else:
        return redirect('/')


class ArticleComment(FormView):
    form_class = CommentForm

    def form_valid(self, form):
        slug = self.kwargs.get('slug')
        article = Article.objects.get(slug=slug)
        comments = article.comments.all()
        if not article.comments.filter(article__comments__extuser=ExtUser.objects.get(user=self.request.user)):
            comment = Comment(body=form.cleaned_data['body'], extuser=self.request.user.extuser)
            comment.save()
            article.comments.add(comment)
            return redirect(reverse_lazy('blog:article_detail', args=[slug]))
        else:
            return redirect(reverse_lazy('blog:article_detail', args=[slug]))

templates/blog/article_detail.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}
    {{ article.title }}
{% endblock %}

{% block main_content %}
    <div class="row">
        <div class="col-md-2">
            <div class="list-group sticky-top">
                    <span class="list-group-item list-group-item-info">
                        Категории
                    </span>
                {% for cat in categories_list %}
                    <a href="{% url 'blog:article_list' cat.slug %}"
                       class="list-group-item list-group-item-action {% if cat.slug == article.slug %}active {% endif %}">{{ cat.title }}</a>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-8">
            <div class="card text-center w-100">
                <div class="card-header">
                    {% for article_cat in article.categorys.all %}{{ article_cat.title }} {% endfor %}
                </div>
                <div class="card-block">
                    <h4 class="card-title">{{ object.title }}</h4>
                    <p class="card-text">
                        <img class="card-img img-fluid" src="/media/{{ object.image }}" alt="{{ object.title }}">
                        {{ object.text |safe }}</p>
                {% if user.is_authenticated %}
                    <button id="like"
                            {% if user.extuser in article.likes.all or user.extuser in article.dislikes.all %}disabled
                            data-toggle="tooltip" data-placement="top" title="Вы уже голосовали" {% endif %}
                            data-like-url="{% url 'blog:article_like' article.slug %}"
                            class="{% if user.extuser in article.likes.all or user.extuser in article.dislikes.all %}disabled{% endif %}">
                        <span id="likes-count">{{ object.likes.count }}</span>
                        <img src="{% static 'img/glyphicons/png/glyphicons-344-thumbs-up.png' %}" alt="Like">
                    </button>
                    <button id="dislike" data-like-url="{% url 'blog:article_like' article.slug %}"
                            {% if user.extuser in article.likes.all or user.extuser in article.dislikes.all %}disabled
                            data-toggle="tooltip" data-placement="top" title="Вы уже голосовали" {% endif %}
                            class="{% if user.extuser in article.likes.all or user.extuser in article.dislikes.all %}disabled{% endif %}">
                        <span id="dislikes-count">{{ object.dislikes.count }}</span>
                        <img src="{% static 'img/glyphicons/png/glyphicons-345-thumbs-down.png' %}" alt="dislike">
                    </button>
                {% endif %}
                </div>
                <div class="card-footer text-muted">
                    {{ article.date }}
                </div>
            </div>
            <h2 class="text-center m-3" style="text-shadow: 5px 5px 10px RGBA(0,0,0,0.3);">Комментарии</h2>
            <div class="article-comments">
                {% for comment in article.comments.all %}
                    <div class="card card-outline-secondary mb-3 text-center">
                        <div class="card-block">
                            <blockquote class="card-blockquote">
                                {{ comment.body | safe }}
                                <footer><cite title="Source Title">&mdash; {{ comment.extuser.user }}.</cite></footer>
                            </blockquote>
                        </div>
                    </div>
                {% endfor %}
                {% if user.is_authenticated and comment_form %}
                    <div class="card card-outline-secondary mb-3 text-center">
                        <div class="card-block">
                            <blockquote class="card-blockquote">
                                <form action="{% url 'blog:article_comment' article.slug %}" method="POST">
                                    {% csrf_token %}
                                    {{ comment_form.body }}<br>
                                    <button type="submit">Оставить комментарий</button>
                                </form>
                                <footer><cite title="Source Title">&mdash; {{ user }}.</cite></footer>
                            </blockquote>
                        </div>
                    </div>
                {% elif user.is_authenticated and not comment_form %}
                    <div class="card card-inverse card-danger text-center">
                        <div class="card-block">
                            <blockquote class="card-blockquote">
                                <p>Вы уже оставляли комментарий</p>
                            </blockquote>
                        </div>
                    </div>
                {% else %}
                    <div class="card card-inverse card-info text-center">
                        <div class="card-block">
                            <blockquote class="card-blockquote">
                                <p>Чтобы оставить комменатрий необходимо <a href="{% url 'city:create_extuser' %}">зарегистрироваться</a><p>
                            </blockquote>
                        </div>
                    </div>
                {% endif %}
            </div>

        </div>
    </div>

{% endblock %}

templates/blog/article_list.html
{% extends 'base/base.html' %}

{% block title %}
    Статьи
{% endblock %}

{% block main_content %}
    <div class="row">
        <div class="col-md-2">
            <div class="list-group">
                    <a class="list-group-item list-group-item-info"
                        href="{% url 'blog:article_list' %}">Категории</a>
                {% for cat in categories_list %}
                    <a href="{% url 'blog:article_list' cat.slug %}"
                       class="list-group-item list-group-item-action {% if cat.slug == category_slug %}active {% endif %}">{{ cat.title }}</a>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-8">
            {% for article in article_list %}
                <div class="card text-center">
                    <div class="card-header">
                    {{ article.city }}
                        ({% for article_cat in article.categorys.all %}{{ article_cat.title }}, {% endfor %})
                    </div>
                    <div class="card-block">
                        <h4 class="card-title">{{ article.title }}</h4>
                        <img class="card-img img-fluid" src="/media/{{ article.image }}" alt="{{ object.title }}">
                        <p class="card-text">{{ article.text | truncatewords_html:60 | safe }}</p>
                        <a href="{% url 'blog:article_detail' article.slug %}" class="btn btn-primary">Читать далее</a>
                    </div>
                </div>
            {% endfor %}

            {% if is_paginated %}
                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center">
                        {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a class="page-link"
                                   href="
{% if category_slug %}
{% url 'blog:article_list' category_slug %}?page={{ page_obj.previous_page_number }}"
{% else %}
{% url 'blog:article_list' %}?page={{ page_obj.previous_page_number }}"
{% endif %}
                                   tabindex="-1">Previous</a>
                            </li>
                        {% endif %}


                        <li class="page-item"><span
                                class="page-link">{{ page_obj.number }} из {{ page_obj.paginator.num_pages }}</span>
                        </li>


                        {% if page_obj.has_next %}
                            <li class="page-item">
                                <a class="page-link"
                                   href="
                                   {% if category_slug %}
                                        {% url 'blog:article_list' category_slug %}?page={{ page_obj.next_page_number }}">
                                   {% else %}
                                           {% url 'blog:article_list' %}?page={{ page_obj.next_page_number }}">Next
                                       </a>
                                   {% endif %}

                            </li>
                        {% endif %}
                    </ul>
                </nav>

            {% endif %}

        </div>
    </div>

{% endblock %}