blog/urls.py
from django.conf.urls import url
from .views import ArticleListView, ArticleDetailView, ArticleLike, ArticleComment


urlpatterns = [
    url(r'^$', ArticleListView.as_view(), name='article_list'),
    url(r'^(?P<category_slug>[\w-]+)/$', ArticleListView.as_view(), name='article_list'),
    url(r'^article/(?P<slug>[-\w]+)/$', ArticleDetailView.as_view(), name='article_detail'),
    url(r'^article/(?P<slug>[-\w]+)/like/$', ArticleLike, name='article_like'),
    url(r'^article/(?P<slug>[-\w]+)/comment/$', ArticleComment.as_view(), name='article_comment'),
]

city/urls.py
from django.conf.urls import url
from .views import CreateExtUser, SuccesPage, LogoutPage, ChooseCity, LoginPage
from django.contrib.auth.views import login

urlpatterns = [
    url(r'^auth/$', CreateExtUser.as_view(), name="create_extuser"),
    url(r'^choose_city/$', ChooseCity.as_view(), name="choose_city"),
    url(r'^success/$', SuccesPage.as_view(), name="success"),
    url(r'^logout/$', LogoutPage.as_view(), name="logout"),
    url(r'^login/$', login, {'template_name': 'city/login.html'}, name='login'),
]

test_the_invaders/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^ext/', include('city.urls', namespace='city')),
    url(r'^', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

city/models.py
from django.db import models
from django.contrib.auth.models import User


class City(models.Model):
    name = models.CharField('Название города', max_length=200)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Город'
        verbose_name_plural = 'Города'


class ExtUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    city = models.ForeignKey(City, verbose_name='Город')

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name = 'Расширенный пользователь'
        verbose_name_plural = 'Расширенные пользователи'

city/forms.py
from .models import ExtUser, City
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelChoiceField, ModelForm
from django.contrib.auth.models import User


class ExtUserForm(UserCreationForm):
    city = ModelChoiceField(City.objects.all(), to_field_name='name')

    def save(self, commit=True):
        user = super(ExtUserForm, self).save(commit=False)
        if commit:
            user.save()
            extuser = ExtUser()
            extuser.user = user
            extuser.city = City.objects.get(name=self.cleaned_data['city'])
            extuser.save()
        return user


class LoginForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']


class ChooseCity(ModelForm):
    city = ModelChoiceField(City.objects.all(), to_field_name='name')

    class Meta:
        fields = ['city']

city/views.py
from django.views.generic import DetailView, CreateView, FormView, TemplateView, RedirectView
from .forms import ExtUserForm, LoginForm
from django.contrib.auth import login, logout, authenticate
from .models import ExtUser, City
from django.contrib.auth.models import User
from django.shortcuts import redirect
from django.core.urlresolvers import reverse_lazy


class SuccesPage(TemplateView):
    template_name = 'base/success.html'


class CreateExtUser(FormView):
    template_name = 'city/create_ext_user.html'
    model = ExtUser
    form_class = ExtUserForm
    success_url = reverse_lazy('city:success')

    def form_valid(self, form):
        login(self.request, form.save(commit=True))
        return super(CreateExtUser, self).form_valid(form)


class ChooseCity(CreateView):
    model = ExtUser
    fields = ['city']
    template_name = 'city/choose_city.html'

    def form_valid(self, form):
        print(form.cleaned_data['city'])
        user = User.objects.get(username=form.data['user'])
        extuser, created = ExtUser.objects.get_or_create(user=user)
        extuser.city = City.objects.get(name=form.cleaned_data['city'])
        extuser.save()
        return redirect(reverse_lazy('city:success'))

    def form_invalid(self, form):
        print('invalid')
        print(form)


class LogoutPage(RedirectView):
    pattern_name = 'success'
    url = reverse_lazy('city:success')

    def get(self, request, *args, **kwargs):
        logout(request)
        return super(LogoutPage, self).get(self, request, *args, **kwargs)


class LoginPage(FormView):
    form_class = LoginForm
    template_name = 'city/login_page.html'
    success_url = reverse_lazy('city:success')

    def form_valid(self, form):
        user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password'])
        if user is not None:
            login(self.request, user)
        else:
            return redirect(reverse_lazy('city:login'))
        return super(LoginPage, self).form_valid(form)

    def form_invalid(self, form):
        return redirect(reverse_lazy('city:login'))

templates/city/choose_city.html
{% extends "base/base.html" %}

{% block title %}
    Регистрация
{% endblock %}

{% block main_content %}
    <div class="row mt-5">
        <div class="col-md-6 push-3">
            {% if not user.is_authenticated %}
                <h2>Необходимо сначала зарегистрироваться</h2>
                <a href="{% url 'city:create_extuser' %}">Страница регистрации</a>
            {% else %}
                <form action="" method="post">
                <div class="form-group">
                    {% csrf_token %}
                        {{ form.city }}
                        <input type="hidden" name="user" value="{{ user }}">
                    <button type="submit">Выбрать</button>
                </div>
                </form>
            {% endif %}</div>

    </div>

{% endblock %}

templates/city/create_ext_user.html
{% extends "base/base.html" %}

{% block title %}
    Регистрация
{% endblock %}

{% block main_content %}
    <div class="row mt-5">
        <div class="col-md-6 push-3">
            {% if not user.is_authenticated %}
                <form action="" method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group">
                            {{ field.errors }}
                            {{ field.label_tag }} {{ field }}
                            {% if field.help_text %}
                                <small id="emailHelp" class="form-text text-muted">{{ field.help_text|safe }}</small>
                            {% endif %}
                        </div>
                    {% endfor %}
                    <button type="submit">Зарегистрироваться</button>
                </form>
            {% else %}
                <h2>Вы уже вошли как {{ user }}</h2>
            {% endif %}</div>

    </div>

{% endblock %}

templates/city/login.html
{% extends "base/base.html" %}

{% block title %}
    Регистрация
{% endblock %}

{% block main_content %}
    <div class="row mt-5">
        <div class="col-md-6 push-3">
            {% if not user.is_authenticated %}
                <form action="" method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group">
                            {{ field.errors }}
                            {{ field.label_tag }} {{ field }}
                            {% if field.help_text %}
                                <small id="emailHelp" class="form-text text-muted">{{ field.help_text|safe }}</small>
                            {% endif %}
                        </div>
                    {% endfor %}
                    <button type="submit">Войти</button>
                </form>
            {% else %}
                <h2>Вы уже вошли как {{ user }}</h2>
            {% endif %}</div>

    </div>

{% endblock %}